---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-test-checker-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configMaps-checker-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs:
    - get
    - list
    - watch
    - patch
    - update
    - create
    - delete
    - post
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configMaps-checker-reader-binding
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: configMaps-checker-reader
subjects:
  - kind: ServiceAccount
    name: chaos-test-checker-sa
---
apiVersion: v1
kind: Pod
metadata:
  name: checker
spec:
  containers:
  - name: checker
    image: docker.io/andreatp/test-checker-app:latest
  restartPolicy: Never
  serviceAccountName: chaos-test-checker-sa
