name: ci

on:
  push:
    branches:
      - main
    pull_requests:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        java-version: [11, 17]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java-version }}
          cache: maven

      - name: Set images UUIDs
        id: images
        run: |
          echo "CHECKER_IMAGE=$(echo ttl.sh/$(uuidgen)-checker:10h | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
          echo "CONTROL_IMAGE=$(echo ttl.sh/$(uuidgen)-control:10h | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"

      - name: Build and push support apps
        working-directory: ./support-apps
        run: make all

      - name: Run the tests
        run: mvn -B verify
