name: ci

on:
  push:
    branches:
      - main
    pull_requests:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java-version: [11, 17]
        http-client: [ "okhttp", "jdkhttp", "vertxhttp"]
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: maven

      - name: Set images UUIDs
        id: images
        run: |
          echo "CHECKER_IMAGE=$(echo ttl.sh/$(uuidgen)-checker:10h | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
          echo "CONTROL_IMAGE=$(echo ttl.sh/$(uuidgen)-control:10h | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
          echo "HTTP_CLIENT=${{ matrix.http-client }}" >> "$GITHUB_ENV"

      - name: Build and push support apps
        working-directory: ./support-apps
        run: make all

      - name: Start minikube
        uses: medyagh/setup-minikube@latest
        with:
          cache: true
          minikube-version: 1.30.1
          # kubernetes-version: v1.27.2
          cpus: 2
          memory: 6000m

      - name: Install Chaos Mesh
        run: |
          curl -sSL https://mirrors.chaos-mesh.org/v2.6.0/install.sh | bash
          kubectl wait --for=condition=Ready pods -n chaos-mesh --all --timeout=600s

      - name: Run the tests
        run: mvn -B verify
